version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    build: .
    ports:
      - "3000:3000"
    container_name: mhstrategy-api
    restart: always
    volumes:
      - ./flask_app:/app/flask_app
    links:
      - db