version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD="466a1ee4eed0338d495cfe18a52a04e54a794e35ff6bc2324e464e0c006efb29"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  web:
    build: .
    ports:
      - "3000:3000"
    container_name: mhstrategy-api
    restart: always
    volumes:
      - ./flask_app:/app/flask_app
    links:
      - db