"""empty message

Revision ID: 08048bfc0a93
Revises: 
Create Date: 2022-04-04 09:00:23.990846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08048bfc0a93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weakness', sa.String(length=255), nullable=False),
    sa.Column('strong', sa.String(length=255), nullable=False),
    sa.Column('build', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=230), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('monster')
    # ### end Alembic commands ###
